import english from '../../public/design-review/index.html?raw';
import arabic from '../content/homepage-ar.html?raw';
import { site } from '../data/site';
import { enhanceHomepage } from './homepage-content';
import { designHomepage } from './homepage-design';

export function homepage(locale: 'en' | 'ar') {
  const ar = locale === 'ar';
  const title = ar ? 'UBAKEL — ذكاء اصطناعي وأتمتة على مقاس عملك' : 'UBAKEL — Custom AI, Automation & Integrations';
  const description = ar ? 'مهام متكررة أقل ووقت أكثر لعملك. حلول أتمتة ومساعدون بالذكاء الاصطناعي وربط أدواتك لإعداد التقارير ومعالجة المستندات ومتابعة الطلبات.' : 'Less busywork. More time for your business. Custom automation, AI assistants and connected tools for reporting, document processing and clearer handoffs.';
  const url = ar ? 'https://ubakel.com/ar/' : 'https://ubakel.com/';
  const labels = ar ? {
    close: 'إغلاق نموذج التواصل', kicker: 'لنبدأ بإجراء واحد', title: 'ما الذي يشغل<br>وقت فريقك؟', intro: 'أخبرنا بما يتكرر أو يتعطّل في عملك. سنراجع طلبك ونتواصل معك لمناقشة الخطوة التالية.',
    name: 'الاسم الكامل', email: 'البريد الإلكتروني', business: 'اسم الشركة', phone: 'رقم واتساب (اختياري)', workflow: 'ما الذي تود تحسينه أو أتمتته؟', placeholder: 'نقضي وقتًا طويلًا في إعداد التقارير من ملفات مختلفة. نستخدم…', submit: 'اطلب مراجعة أولية مجانية', sending: 'جارٍ إرسال الطلب…', success: 'وصل طلبك. شكرًا لك! سنتواصل معك لمناقشة طريقة عملك والخطوة التالية.', error: 'تعذّر إرسال الطلب. احتفظنا بما كتبته. حاول مرة أخرى، أو تواصل معنا عبر البريد الإلكتروني.', invalid: 'يرجى تعبئة هذا الحقل.', emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح، مثل name@company.com.', help: 'جميع الحقول مطلوبة باستثناء رقم واتساب. تكفي بضع جمل، ولا تحتاج إلى وصف تقني.', privacy: 'ابدأ بوصف عام. لا ترسل كلمات مرور أو بيانات سرية تخص العملاء.', next: 'الخطوة التالية: نراجع طلبك ونتواصل معك. هذا الطلب لا يحجز موعد اجتماع.', note: 'يُرسل هذا النموذج طلبك إلى فريق UBAKEL عبر البريد الإلكتروني.', direct: 'للتواصل مباشرةً:',
  } : {
    close: 'Close contact form', kicker: 'START WITH ONE WORKFLOW', title: 'What’s keeping<br>your team busy?', intro: 'Tell us what repeats or gets stuck. We’ll review your request and get in touch to discuss the next step.',
    name: 'Full name', email: 'Email address', business: 'Company', phone: 'WhatsApp number (optional)', workflow: 'What would you like to improve or automate?', placeholder: 'We spend hours preparing reports from different files. We use…', submit: 'Request a free workflow review', sending: 'Sending your request…', success: 'Your request has been received. Thank you! We’ll be in touch to discuss your workflow and the next step.', error: 'We couldn’t send your request. Your entries have been kept. Please try again, or contact us by email.', invalid: 'Please complete this field.', emailInvalid: 'Enter a valid email address, such as name@company.com.', help: 'All fields are required except WhatsApp. A few sentences are enough; no technical brief needed.', privacy: 'Start with a general description. Please leave out passwords and confidential customer information.', next: 'Next: we review your request and get in touch. This request does not reserve a meeting time.', note: 'This form sends your enquiry to the UBAKEL team by email.', direct: 'Contact us directly:',
  };
  const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
  const contact = `<dialog id="contact-dialog" class="contact-dialog" aria-labelledby="contact-title"><div class="contact-toolbar"><span class="eyebrow">${labels.kicker}</span><button class="dialog-close" data-close="contact-dialog" aria-label="${labels.close}">×</button></div><h2 id="contact-title">${labels.title}</h2><p class="dialog-intro">${labels.intro}</p>
    <p class="form-help" id="form-help">${labels.help}</p><form id="contact-form" aria-describedby="form-help form-next" action="https://api.web3forms.com/submit" method="POST" data-sending="${labels.sending}" data-success="${labels.success}" data-error="${labels.error}" data-invalid="${labels.invalid}" data-email-invalid="${labels.emailInvalid}">
      <input type="hidden" name="access_key" value="${escape(site.web3formsKey)}"><input type="hidden" name="subject" value="New workflow audit request — UBAKEL"><input type="hidden" name="from_name" value="UBAKEL Website"><input type="hidden" name="redirect" value="https://web3forms.com/success"><input type="checkbox" name="botcheck" hidden tabindex="-1" autocomplete="off">
      <div class="form-row"><label>${labels.name}<input aria-label="${labels.name}" id="name" name="name" autocomplete="name" aria-describedby="name-error" required maxlength="100"><span class="field-error" id="name-error" hidden></span></label><label>${labels.email}<input aria-label="${labels.email}" id="email" name="email" type="email" autocomplete="email" dir="ltr" aria-describedby="email-error" required maxlength="254"><span class="field-error" id="email-error" hidden></span></label></div>
      <div class="form-row"><label>${labels.business}<input aria-label="${labels.business}" id="business" name="company" autocomplete="organization" aria-describedby="business-error" required maxlength="150"><span class="field-error" id="business-error" hidden></span></label><label>${labels.phone}<input id="phone" name="phone" type="tel" autocomplete="tel" dir="ltr" maxlength="50"></label></div>
      <label>${labels.workflow}<textarea aria-label="${labels.workflow}" id="workflow" name="message" placeholder="${labels.placeholder}" aria-describedby="workflow-help workflow-error" required rows="3" maxlength="2000"></textarea><span class="field-hint" id="workflow-help">${labels.privacy}</span><span class="field-error" id="workflow-error" hidden></span></label>
      <button type="submit" class="button dark"><span id="submit-label">${labels.submit}</span><span aria-hidden="true">↗</span></button><p class="form-next" id="form-next">${labels.next}</p><p class="form-note">${labels.note} ${labels.direct} <a href="mailto:info@ubakel.com" dir="ltr">info@ubakel.com</a></p><p id="form-status" role="status" aria-live="polite" hidden></p>
    </form></dialog>`;
  const metadata = `<link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="https://ubakel.com/"><link rel="alternate" hreflang="ar" href="https://ubakel.com/ar/"><link rel="alternate" hreflang="ms" href="https://ubakel.com/ms/"><link rel="alternate" hreflang="x-default" href="https://ubakel.com/"><meta property="og:site_name" content="UBAKEL"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${description}"><meta property="og:image" content="https://ubakel.com/og-image.jpg"><meta property="og:locale" content="${ar ? 'ar_AR' : 'en_US'}"><meta name="twitter:card" content="summary_large_image">${ar ? '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Cairo:wght@600;700;800&display=swap" rel="stylesheet">' : ''}`;
  const languageLinks = `<a href="/" lang="en" data-lang="en"${ar ? '' : ' aria-current="page"'}>English</a><a href="/ar/" lang="ar" data-lang="ar"${ar ? ' aria-current="page"' : ''}>العربية</a><a href="/ms/" lang="ms" data-lang="ms">Bahasa Melayu</a>`;
  const html = enhanceHomepage(ar ? arabic : english, locale)
    .replace(/<title>.*?<\/title>/, `<title>${title}</title>`)
    .replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${description}">`)
    .replace('<meta name="robots" content="noindex, nofollow">', metadata)
    .replace('<link rel="stylesheet" href="style.css">', '<link rel="stylesheet" href="/design-review/style.css"><link rel="stylesheet" href="/homepage.css">')
    .replace('src="app.js"', 'src="/homepage.js"')
    .replaceAll('assets/', '/design-review/assets/')
    .replace(/<dialog id="contact-dialog"[\s\S]*?<\/dialog>/, contact)
    .replace('</main>', `<noscript><p style="padding:24px;text-align:center"><a href="/contact/">${ar ? 'أرسل طلبك عبر نموذج التواصل' : 'Send your enquiry through the contact form'}</a></p></noscript></main>`)
    .replace('<div class="header-actions">', `<div class="header-actions"><details class="language-menu"><summary aria-label="${ar ? 'تغيير اللغة' : 'Change language'}">${ar ? 'ع' : 'EN'}</summary><nav aria-label="${ar ? 'اللغة' : 'Language'}">${languageLinks}</nav></details>`)
    .replace('</footer>', `<nav class="languages" aria-label="${ar ? 'اللغة' : 'Language'}">${languageLinks}</nav></footer>`);
  return designHomepage(html, locale);
}
